from peewee import *

database = SqliteDatabase('/Users/linlyu/Desktop/Bee2waste.db')

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class W3(BaseModel):
    bulky_ = TextField(column_name='Bulky%', null=True)
    electronics_ = TextField(column_name='Electronics%', null=True)
    food_ = TextField(column_name='Food%', null=True)
    glass_ = TextField(column_name='Glass%', null=True)
    metal_ = TextField(column_name='Metal%', null=True)
    moisture = TextField(column_name='Moisture', null=True)
    others_ = TextField(column_name='Others%', null=True)
    paper_ = TextField(column_name='Paper%', null=True)
    plastics_ = TextField(column_name='Plastics%', null=True)
    ref_ = TextField(column_name='Ref.', null=True)
    textile_ = TextField(column_name='Textile%', null=True)
    total_quantity = TextField(column_name='TotalQuantity', null=True)
    unit = TextField(column_name='Unit', null=True)
    w3_id = AutoField(column_name='W3.ID', null=True)
    waste_type = TextField(column_name='WasteType', null=True)
    yard_ = TextField(column_name='Yard%', null=True)

    class Meta:
        table_name = 'W3'

class Sw3(BaseModel):
    area_km2_ = TextField(column_name='Area(km2)', null=True)
    city__region_s6_1_ = TextField(column_name='City/Region(S6.1)', null=True)
    day_s8_1_ = TextField(column_name='Day(S8.1)', null=True)
    education_s2_1_ = TextField(column_name='Education(S2.1)', null=True)
    gdp__capita_s4_1_ = TextField(column_name='GDP/Capita$(S4.1)', null=True)
    household_size_s1_3_ = TextField(column_name='HouseholdSize(S1.3)', null=True)
    pop__density_s1_2_ = TextField(column_name='Pop.Density(S1.2)', null=True)
    population_million_s1_1_ = TextField(column_name='PopulationMillion(S1.1)', null=True)
    precipitation_cm_s5_1_ = TextField(column_name='Precipitation(cm)(S5.1)', null=True)
    state__country_s6_2_ = TextField(column_name='State/Country(S6.2)', null=True)
    sustainabilitygoals_s7_1_ = TextField(column_name='Sustainabilitygoals(S7.1)', null=True)
    temperature_c_s5_2_ = TextField(column_name='TemperatureC(S5.2)', null=True)
    w3_id = ForeignKeyField(column_name='W3.ID', field='w3_id', model=W3, null=True, primary_key=True)
    waste_regulations_s7_2_ = TextField(column_name='WasteRegulations(S7.2)', null=True)
    year_s8_2_ = TextField(column_name='Year(S8.2)', null=True)

    class Meta:
        table_name = 'S-W3'

class W1(BaseModel):
    code = DecimalField(column_name='Code', null=True, primary_key=True)
    description = TextField(column_name='Description', null=True)
    note = TextField(column_name='Note', null=True)
    waste_type = TextField(column_name='WasteType', null=True)

    class Meta:
        table_name = 'W1'

class W1W2(BaseModel):
    code = ForeignKeyField(column_name='Code', field='code', model=W1, null=True, primary_key=True)
    w2_10_magnetic_susceptibility = TextField(column_name='W2.10MagneticSusceptibility', null=True)
    w2_11_electrical_conductivity = TextField(column_name='W2.11ElectricalConductivity', null=True)
    w2_12_individualizationdegree_01_ = TextField(column_name='W2.12Individualizationdegree[01]', null=True)
    w2_13_elasticity = TextField(column_name='W2.13Elasticity', null=True)
    w2_14_friction_rugosity = TextField(column_name='W2.14Friction/rugosity', null=True)
    w2_15_hydrophobicity_k_ = TextField(column_name='W2.15Hydrophobicity(k)', null=True)
    w2_16_humidity = TextField(column_name='W2.16Humidity', null=True)
    w2_17_ashcontent = TextField(column_name='W2.17Ashcontent', null=True)
    w2_18_volatilematter = TextField(column_name='W2.18Volatilematter', null=True)
    w2_19_fixed_carbon = TextField(column_name='W2.19FixedCarbon', null=True)
    w2_1_shape = TextField(column_name='W2.1Shape', null=True)
    w2_20_c = TextField(column_name='W2.20%C', null=True)
    w2_21_h = TextField(column_name='W2.21%H', null=True)
    w2_22_o = TextField(column_name='W2.22%O', null=True)
    w2_23_n = TextField(column_name='W2.23%N', null=True)
    w2_24_s = TextField(column_name='W2.24%S', null=True)
    w2_25__cl = TextField(column_name='W2.25%Cl', null=True)
    w2_26__na = TextField(column_name='W2.26%Na', null=True)
    w2_27_k = TextField(column_name='W2.27%K', null=True)
    w2_28__metals = TextField(column_name='W2.28%Metals', null=True)
    w2_29__alkalines = TextField(column_name='W2.29%Alkalines', null=True)
    w2_2_color = TextField(column_name='W2.2Color', null=True)
    w2_30_contaminants = TextField(column_name='W2.30Contaminants', null=True)
    w2_30_heat_value = TextField(column_name='W2.30HeatValue', null=True)
    w2_31_recyclability = TextField(column_name='W2.31Recyclability', null=True)
    w2_32_biodegradability = TextField(column_name='W2.32Biodegradability', null=True)
    w2_33_value = TextField(column_name='W2.33Value', null=True)
    w2_34_tradability = TextField(column_name='W2.34Tradability', null=True)
    w2_3_hardness = TextField(column_name='W2.3Hardness', null=True)
    w2_4_brightness = TextField(column_name='W2.4Brightness', null=True)
    w2_5_nir_lightreflection_ʎ_ = TextField(column_name='W2.5NIRLightreflection(ʎ)', null=True)
    w2_6_photoemissionlevel = TextField(column_name='W2.6Photoemissionlevel', null=True)
    w2_7_opacity = TextField(column_name='W2.7Opacity', null=True)
    w2_8_particle_size = TextField(column_name='W2.8ParticleSize', null=True)
    w2_9_density_kg_m_3_ = TextField(column_name='W2.9Density[kg/m^3]', null=True)
    w3sensitive_ = TextField(column_name='W3sensitive?', null=True)
    wastes_w1_ = TextField(column_name='Wastes(W1)', null=True)

    class Meta:
        table_name = 'W1-W2'

class W1W4(BaseModel):
    code = ForeignKeyField(column_name='Code', field='code', model=W1, null=True, primary_key=True)
    w4_c1 = TextField(column_name='W4.C1', null=True)
    w4_c2 = TextField(column_name='W4.C2', null=True)
    w4_c3 = TextField(column_name='W4.C3', null=True)
    w4_c4 = TextField(column_name='W4.C4', null=True)
    w4_c5 = TextField(column_name='W4.C5', null=True)
    w4_ft1 = TextField(column_name='W4.FT1', null=True)
    w4_ft2 = TextField(column_name='W4.FT2', null=True)
    w4_ft2_1 = TextField(column_name='W4.FT2.1', null=True)
    w4_ft2_2 = TextField(column_name='W4.FT2.2', null=True)
    w4_ft2_3 = TextField(column_name='W4.FT2.3', null=True)
    w4_ft3 = TextField(column_name='W4.FT3', null=True)
    w4_ft3_1 = TextField(column_name='W4.FT3.1', null=True)
    w4_ft3_2 = TextField(column_name='W4.FT3.2', null=True)
    w4_ft3_3 = TextField(column_name='W4.FT3.3', null=True)
    w4_ft3_4 = TextField(column_name='W4.FT3.4', null=True)
    w4_ft4 = TextField(column_name='W4.FT4', null=True)
    w4_ft4_1 = TextField(column_name='W4.FT4.1', null=True)
    w4_ft4_2 = TextField(column_name='W4.FT4.2', null=True)
    w4_ft4_3 = TextField(column_name='W4.FT4.3', null=True)
    w4_ft4_4 = TextField(column_name='W4.FT4.4', null=True)
    w4_ft4_5 = TextField(column_name='W4.FT4.5', null=True)
    w4_ft5 = TextField(column_name='W4.FT5', null=True)
    w4_ft5_1 = TextField(column_name='W4.FT5.1', null=True)
    w4_ft5_2 = TextField(column_name='W4.FT5.2', null=True)
    w4_ft6 = TextField(column_name='W4.FT6', null=True)
    w4_ft6_1_1 = TextField(column_name='W4.FT6.1.1', null=True)
    w4_ft6_1_2 = TextField(column_name='W4.FT6.1.2', null=True)
    w4_ft6_1_3 = TextField(column_name='W4.FT6.1.3', null=True)
    w4_ft6_2_1 = TextField(column_name='W4.FT6.2.1', null=True)
    w4_ft6_2_2 = TextField(column_name='W4.FT6.2.2', null=True)
    w4_ft6_3 = TextField(column_name='W4.FT6.3', null=True)
    w4_ft6_4 = TextField(column_name='W4.FT6.4', null=True)
    w4_ft7 = TextField(column_name='W4.FT7', null=True)
    w4_ft8_1 = TextField(column_name='W4.FT8.1', null=True)
    w4_ft8_2 = TextField(column_name='W4.FT8.2', null=True)
    w4_g1 = TextField(column_name='W4.G1', null=True)
    w4_g2 = TextField(column_name='W4.G2', null=True)
    w4_g3 = TextField(column_name='W4.G3', null=True)
    w4_g4 = TextField(column_name='W4.G4', null=True)
    w4_g5 = TextField(column_name='W4.G5', null=True)
    w4_g6 = TextField(column_name='W4.G6', null=True)
    w4_g7 = TextField(column_name='W4.G7', null=True)
    w4_g8 = TextField(column_name='W4.G8', null=True)
    w4_p1 = TextField(column_name='W4.P1', null=True)
    w4_p1_1 = TextField(column_name='W4.P1.1', null=True)
    w4_p1_10 = TextField(column_name='W4.P1.10', null=True)
    w4_p1_2 = TextField(column_name='W4.P1.2', null=True)
    w4_p1_3 = TextField(column_name='W4.P1.3', null=True)
    w4_p1_4 = TextField(column_name='W4.P1.4', null=True)
    w4_p1_5 = TextField(column_name='W4.P1.5', null=True)
    w4_p1_6 = TextField(column_name='W4.P1.6', null=True)
    w4_p1_7 = TextField(column_name='W4.P1.7', null=True)
    w4_p1_8 = TextField(column_name='W4.P1.8', null=True)
    w4_p1_9 = TextField(column_name='W4.P1.9', null=True)
    w4_p2 = TextField(column_name='W4.P2', null=True)
    w4_p2_1 = TextField(column_name='W4.P2.1', null=True)
    w4_p2_2 = TextField(column_name='W4.P2.2', null=True)
    w4_p2_3 = TextField(column_name='W4.P2.3', null=True)
    w4_p2_4 = TextField(column_name='W4.P2.4', null=True)
    w4_p3 = TextField(column_name='W4.P3', null=True)
    w4_p3_1 = TextField(column_name='W4.P3.1', null=True)
    w4_p3_2 = TextField(column_name='W4.P3.2', null=True)
    w4_p4 = TextField(column_name='W4.P4', null=True)
    w4_p5 = TextField(column_name='W4.P5', null=True)
    w4_p5_1 = TextField(column_name='W4.P5.1', null=True)
    w4_p5_2 = TextField(column_name='W4.P5.2', null=True)
    w4_p5_3 = TextField(column_name='W4.P5.3', null=True)
    w4_s1 = TextField(column_name='W4.S1', null=True)
    w4_s2 = TextField(column_name='W4.S2', null=True)
    w4_s3 = TextField(column_name='W4.S3', null=True)
    w4_s4 = TextField(column_name='W4.S4', null=True)
    w4_t1 = TextField(column_name='W4.T1', null=True)
    w4_t2 = TextField(column_name='W4.T2', null=True)
    w4_t3 = TextField(column_name='W4.T3', null=True)
    w4_t4 = TextField(column_name='W4.T4', null=True)
    wastes_w1_ = TextField(column_name='Wastes(W1)', null=True)

    class Meta:
        table_name = 'W1-W4'

class W2W4(BaseModel):
    code = TextField(column_name='Code', null=True)
    w4_c1 = TextField(column_name='W4.C1', null=True)
    w4_c2 = TextField(column_name='W4.C2', null=True)
    w4_c3 = TextField(column_name='W4.C3', null=True)
    w4_c4 = TextField(column_name='W4.C4', null=True)
    w4_c5 = TextField(column_name='W4.C5', null=True)
    w4_ft1 = TextField(column_name='W4.FT1', null=True)
    w4_ft2 = TextField(column_name='W4.FT2', null=True)
    w4_ft2_1 = TextField(column_name='W4.FT2.1', null=True)
    w4_ft2_2 = TextField(column_name='W4.FT2.2', null=True)
    w4_ft2_3 = TextField(column_name='W4.FT2.3', null=True)
    w4_ft3 = TextField(column_name='W4.FT3', null=True)
    w4_ft3_1 = TextField(column_name='W4.FT3.1', null=True)
    w4_ft3_2 = TextField(column_name='W4.FT3.2', null=True)
    w4_ft3_3 = TextField(column_name='W4.FT3.3', null=True)
    w4_ft3_4 = TextField(column_name='W4.FT3.4', null=True)
    w4_ft4 = TextField(column_name='W4.FT4', null=True)
    w4_ft4_1 = TextField(column_name='W4.FT4.1', null=True)
    w4_ft4_2 = TextField(column_name='W4.FT4.2', null=True)
    w4_ft4_3 = TextField(column_name='W4.FT4.3', null=True)
    w4_ft4_4 = TextField(column_name='W4.FT4.4', null=True)
    w4_ft4_5 = TextField(column_name='W4.FT4.5', null=True)
    w4_ft5 = TextField(column_name='W4.FT5', null=True)
    w4_ft5_1 = TextField(column_name='W4.FT5.1', null=True)
    w4_ft5_2 = TextField(column_name='W4.FT5.2', null=True)
    w4_ft6 = TextField(column_name='W4.FT6', null=True)
    w4_ft6_1_1 = TextField(column_name='W4.FT6.1.1', null=True)
    w4_ft6_1_2 = TextField(column_name='W4.FT6.1.2', null=True)
    w4_ft6_1_3 = TextField(column_name='W4.FT6.1.3', null=True)
    w4_ft6_2_1 = TextField(column_name='W4.FT6.2.1', null=True)
    w4_ft6_2_2 = TextField(column_name='W4.FT6.2.2', null=True)
    w4_ft6_3 = TextField(column_name='W4.FT6.3', null=True)
    w4_ft6_4 = TextField(column_name='W4.FT6.4', null=True)
    w4_ft7 = TextField(column_name='W4.FT7', null=True)
    w4_ft8_1 = TextField(column_name='W4.FT8.1', null=True)
    w4_ft8_2 = TextField(column_name='W4.FT8.2', null=True)
    w4_g1 = TextField(column_name='W4.G1', null=True)
    w4_g2 = TextField(column_name='W4.G2', null=True)
    w4_g3 = TextField(column_name='W4.G3', null=True)
    w4_g4 = TextField(column_name='W4.G4', null=True)
    w4_g5 = TextField(column_name='W4.G5', null=True)
    w4_g6 = TextField(column_name='W4.G6', null=True)
    w4_g7 = TextField(column_name='W4.G7', null=True)
    w4_g8 = TextField(column_name='W4.G8', null=True)
    w4_p1 = TextField(column_name='W4.P1', null=True)
    w4_p1_1 = TextField(column_name='W4.P1.1', null=True)
    w4_p1_10 = TextField(column_name='W4.P1.10', null=True)
    w4_p1_2 = TextField(column_name='W4.P1.2', null=True)
    w4_p1_3 = TextField(column_name='W4.P1.3', null=True)
    w4_p1_4 = TextField(column_name='W4.P1.4', null=True)
    w4_p1_5 = TextField(column_name='W4.P1.5', null=True)
    w4_p1_6 = TextField(column_name='W4.P1.6', null=True)
    w4_p1_7 = TextField(column_name='W4.P1.7', null=True)
    w4_p1_8 = TextField(column_name='W4.P1.8', null=True)
    w4_p1_9 = TextField(column_name='W4.P1.9', null=True)
    w4_p2 = TextField(column_name='W4.P2', null=True)
    w4_p2_1 = TextField(column_name='W4.P2.1', null=True)
    w4_p2_2 = TextField(column_name='W4.P2.2', null=True)
    w4_p2_3 = TextField(column_name='W4.P2.3', null=True)
    w4_p2_4 = TextField(column_name='W4.P2.4', null=True)
    w4_p3 = TextField(column_name='W4.P3', null=True)
    w4_p3_1 = TextField(column_name='W4.P3.1', null=True)
    w4_p3_2 = TextField(column_name='W4.P3.2', null=True)
    w4_p4 = TextField(column_name='W4.P4', null=True)
    w4_p5 = TextField(column_name='W4.P5', null=True)
    w4_p5_1 = TextField(column_name='W4.P5.1', null=True)
    w4_p5_2 = TextField(column_name='W4.P5.2', null=True)
    w4_p5_3 = TextField(column_name='W4.P5.3', null=True)
    w4_s1 = TextField(column_name='W4.S1', null=True)
    w4_s2 = TextField(column_name='W4.S2', null=True)
    w4_s3 = TextField(column_name='W4.S3', null=True)
    w4_s4 = TextField(column_name='W4.S4', null=True)
    w4_t1 = TextField(column_name='W4.T1', null=True)
    w4_t2 = TextField(column_name='W4.T2', null=True)
    w4_t3 = TextField(column_name='W4.T3', null=True)
    w4_t4 = TextField(column_name='W4.T4', null=True)
    waste_property = TextField(column_name='WasteProperty', null=True)
    field30 = TextField(null=True)

    class Meta:
        table_name = 'W2-W4'
        primary_key = False

class W3W4(BaseModel):
    collection = TextField(column_name='Collection', null=True)
    final_treatment = TextField(column_name='FinalTreatment', null=True)
    generation = TextField(column_name='Generation', null=True)
    processing = TextField(column_name='Processing', null=True)
    storage = TextField(column_name='Storage', null=True)
    transportation = TextField(column_name='Transportation', null=True)
    w3_id = ForeignKeyField(column_name='W3.ID', field='w3_id', model=W3, null=True)
    field11 = TextField(null=True)
    field13 = TextField(null=True)
    field14 = TextField(null=True)
    field15 = TextField(null=True)
    field3 = TextField(null=True)
    field5 = TextField(null=True)
    field7 = TextField(null=True)
    field9 = TextField(null=True)

    class Meta:
        table_name = 'W3-W4'
        primary_key = False

class W3W5(BaseModel):
    city_s6_1_ = TextField(column_name='City(S6.1)', null=True)
    collection = TextField(column_name='Collection', null=True)
    efficiency = TextField(column_name='Efficiency', null=True)
    environmental_performance = TextField(column_name='EnvironmentalPerformance', null=True)
    final_treatment = TextField(column_name='FinalTreatment', null=True)
    financial_performance = TextField(column_name='FinancialPerformance', null=True)
    generation = TextField(column_name='Generation', null=True)
    processing = TextField(column_name='Processing', null=True)
    societal_performance = TextField(column_name='SocietalPerformance', null=True)
    storage = TextField(column_name='Storage', null=True)
    transportation = TextField(column_name='Transportation', null=True)
    w3_id = IntegerField(column_name='W3.ID', null=True)
    year_s8_2_ = TextField(column_name='Year(S8.2)', null=True)

    class Meta:
        table_name = 'W3-W5'
        primary_key = False

class W4P(BaseModel):
    efficiency = TextField(column_name='Efficiency', null=True)
    environmental = TextField(column_name='Environmental', null=True)
    investment = TextField(column_name='Investment', null=True)
    operation_cost = TextField(column_name='OperationCost', null=True)
    swms_component = TextField(column_name='SWMSComponent', null=True)
    social = TextField(column_name='Social', null=True)
    sub_processes = TextField(column_name='Sub-processes', null=True)
    technology = TextField(column_name='Technology', null=True)
    technology_code = TextField(column_name='TechnologyCode', null=True, primary_key=True)

    class Meta:
        table_name = 'W4-P'

